<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_www.mcdonalds.comMcDonalds Burgers, Fries_e03699</name>
   <tag></tag>
   <elementGuidId>edb1a14a-4bcc-4a0b-a964-c890bb5db71d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-ib.fz-20.lh-26.td-hu.tc.va-bot.mxw-100p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad118716-b40d-4cbc-b717-e4eea0b1b277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>4c99bb18-8cd1-4c4c-914f-dfe840e745e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>95498df3-4fa2-4064-b6b2-387ba678d20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>08531e6e-90b1-4802-b7a0-8d3e88d7a526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>f87c683f-0807-4f5a-8fe0-964556e45d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mcdonalds.com/us/en-us.html</value>
      <webElementGuid>d13a41c0-2bbd-4ab2-8b92-c45400535613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-058</name>
      <type>Main</type>
      <value>60f0c3f2307aa8</value>
      <webElementGuid>2ebc0120-8ace-4cae-b797-8df3b6122db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>McDonald's: Burgers, Fries &amp; More. Quality Ingredients.</value>
      <webElementGuid>7e02b8a7-4573-401c-b623-5ed00f93bc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.mcdonalds.comMcDonald's: Burgers, Fries &amp; More. Quality Ingredients.</value>
      <webElementGuid>ea8a25f0-ea7c-480d-9c2e-28e6a71e084f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg  searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd fst lst algo algo-sr relsrch richAlgo&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>28ebff92-a84d-494d-8343-c099cda5bf7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>3e10cba9-d04e-43ef-8878-eb45ec5e14b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mcdonalds.com/us/en-us.html')]</value>
      <webElementGuid>369d214a-84d8-4cac-b0a2-04225fde1588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>2f92c78c-d239-4aed-9191-6db38548d98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mcdonalds.com/us/en-us.html' and (text() = concat(&quot;www.mcdonalds.comMcDonald&quot; , &quot;'&quot; , &quot;s: Burgers, Fries &amp; More. Quality Ingredients.&quot;) or . = concat(&quot;www.mcdonalds.comMcDonald&quot; , &quot;'&quot; , &quot;s: Burgers, Fries &amp; More. Quality Ingredients.&quot;))]</value>
      <webElementGuid>1874ba71-07b4-41f2-8945-23853acf0ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
