<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_reg.pbru.ac.th  register</name>
   <tag></tag>
   <elementGuidId>5ea76e87-38a5-4180-b058-4836cb12a1d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad48f178-3bde-4c51-85e0-57861b6789c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p mt-8</value>
      <webElementGuid>e8dd2116-f64e-4499-8ba3-e52e202f1830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>730f25a9-859b-4fbe-80c3-7171f517bd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://reg.pbru.ac.th/register/</value>
      <webElementGuid>2edbab23-22af-4c4f-8b23-c111c9447897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>1d411eac-07eb-4401-8543-2724ee3c3160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4d80cc6e-777a-4500-ae59-c5ceb0343477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-2d8</name>
      <type>Main</type>
      <value>65a63bc35a7d8</value>
      <webElementGuid>c798e57d-2a37-4c7d-8c90-2c2c08a2f5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี</value>
      <webElementGuid>9961541c-453e-4d45-b81d-ad5f80199e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>reg.pbru.ac.th · registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี</value>
      <webElementGuid>7ff58f0c-7584-4b21-9d42-5bd2d83f3753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd algo algo-sr relsrch fst Sr&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p mt-8&quot;]</value>
      <webElementGuid>3859dbbe-6198-4ad0-930f-7aa27ac05ddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>e033f854-c9d2-430c-ab8d-efc137203fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://reg.pbru.ac.th/register/')]</value>
      <webElementGuid>26b8779b-082a-4dba-8561-c75fbd0704f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>a7eb8bdc-8a47-4870-9573-59779aad3e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://reg.pbru.ac.th/register/' and (text() = 'reg.pbru.ac.th · registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี' or . = 'reg.pbru.ac.th · registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี')]</value>
      <webElementGuid>baa5a2a0-ef84-4862-a69c-62db2180925a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
